repos:
  - repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v5.0.0
    hooks:
      - id: detect-private-key
      - id: detect-aws-credentials
        args: ['--allow-missing-credentials']
      - id: mixed-line-ending
      - id: trailing-whitespace
      - id: check-merge-conflict
  - repo: https://github.com/Yelp/detect-secrets
    rev: v1.5.0
    hooks:
      - id: detect-secrets
        args: ["--baseline", ".secrets.baseline"]
        exclude: package.lock.json
  - repo: https://github.com/Lucas-C/pre-commit-hooks
    rev: v1.5.5
    hooks:
      - id: remove-tabs
      - id: remove-crlf
  - repo: https://github.com/mattlqx/pre-commit-search-and-replace
    rev: v1.1.8
    hooks:
      - id: search-and-replace
        stages: [commit-msg, pre-commit]
  - repo: https://github.com/alessandrojcm/commitlint-pre-commit-hook
    rev: v9.18.0
    hooks:
      - id: commitlint
        stages: [commit-msg]
        args: ['--verbose']
        verbose: true  # print warnings
  - repo: https://github.com/bridgecrewio/checkov.git
    rev: '3.2.296'
    hooks:
      - id: checkov
        verbose: true
        args: [--soft-fail]
  - repo: https://github.com/pre-commit/mirrors-eslint
    rev: v9.14.0
    hooks:
      - id: eslint
        files: \.[jt]sx?$ # *.js, *.jsx, *.ts and *.tsx
        types: [file]
  - repo: https://github.com/pre-commit/mirrors-prettier
    rev: v4.0.0-alpha.8
    hooks:
      - id: prettier
        types_or: ["javascript", "ts", "json"]
  - repo: https://github.com/aws-cloudformation/cfn-lint
    rev: v1.19.0
    hooks:
      - id: cfn-lint
        files: .template\.ya?ml$