export const constants = {
	DEV_CRI_F2F_API_URL: process.env.DEV_CRI_F2F_API_URL,
	DEV_IPV_F2F_STUB_URL: process.env.DEV_IPV_F2F_STUB_URL,
	DEV_F2F_YOTI_STUB_URL: process.env.DEV_F2F_YOTI_STUB_URL,
	DEV_F2F_EXPIRED_ACCESS_TOKEN: process.env.DEV_F2F_EXPIRED_ACCESS_TOKEN,
	DEV_F2F_MISSING_SUB_ACCESS_TOKEN: process.env.DEV_F2F_MISSING_SUB_ACCESS_TOKEN,
	DEV_F2F_IPV_CORE_QUEUE_URL: process.env.DEV_F2F_IPV_CORE_QUEUE_URL,
	DEV_F2F_TEST_HARNESS_URL: process.env.DEV_F2F_TEST_HARNESS_URL,
	DEV_F2F_SESSION_TABLE_NAME: "session-f2f-cri-ddb",
	GOVUKNOTIFYAPI: process.env.GOVUKNOTIFYAPI,
	DEV_F2F_PO_STUB_URL: QA_CHANGES,
};
