export const constants = {
	DEV_CRI_F2F_API_URL: process.env.DEV_CRI_F2F_API_URL,
	DEV_IPV_F2F_STUB_URL: process.env.DEV_IPV_F2F_STUB_URL,
	DEV_F2F_YOTI_STUB_URL: process.env.DEV_F2F_YOTI_STUB_URL,
	DEV_F2F_EXPIRED_ACCESS_TOKEN: process.env.DEV_F2F_EXPIRED_ACCESS_TOKEN,
	DEV_F2F_MISSING_SUB_ACCESS_TOKEN: process.env.DEV_F2F_MISSING_SUB_ACCESS_TOKEN,
	DEV_F2F_IPV_CORE_QUEUE_URL: process.env.DEV_F2F_IPV_CORE_QUEUE_URL,
};
