version = 0.1
[dev]
[dev.deploy]
[dev.deploy.parameters]
stack_name = "f2f-yoti-stub-joe"
s3_prefix = "f2f-yoti-stub"
region = "eu-west-2"
confirm_changeset = false
capabilities = "CAPABILITY_IAM"
parameter_overrides = "CodeSigningConfigArn=\"none\" Environment=\"dev\" PermissionsBoundary=\"none\" SecretPrefix=\"none\" VpcStackName=\"vpc-cri\" L2DynamoStackName=\"yoti-stub-dynamo\" L2KMSStackName=\"infra-l2-kms\""
image_repositories = []
