version = 0.1
[dev]
[dev.deploy]
[dev.deploy.parameters]
stack_name = "f2f-test-harness-viveakv"
s3_prefix = "f2f-test-harness-viveakv"
region = "eu-west-2"
confirm_changeset = false
capabilities = "CAPABILITY_IAM"
parameter_overrides = "CodeSigningConfigArn=\"none\" Environment=\"dev\" PermissionsBoundary=\"none\" SecretPrefix=\"none\" VpcStackName=\"vpc-cri\" BackendStack=\"backend-viveak1\""
image_repositories = []
