export enum YotiDocumentTypesEnum {
	UKPASSPORT = "PASSPORT",
	UKPHOTOCARDDL = "DRIVING_LICENCE",
	NONUKPASSPORT = "PASSPORT",
	EUPHOTOCARDDL = "DRIVING_LICENCE",
	EEAIDENTITYCARD = "NATIONAL_ID",
}

export const YOTI_DOCUMENT_COUNTRY_CODE = "GBR";

export const YOTI_DOCUMENT_COUNTRY = "United Kingdom";

export const YOTI_ADDRESS_FORMAT_CODE = 1;

export const YOTI_SCHEME_CHECK = "UK_GDS";

export const DOCUMENT_TYPES_WITH_CHIPS = ["PASSPORT", "NATIONAL_ID"];

export enum YotiSessionDocument {
	COMPLETED = "COMPLETED",
	APPROVE = "APPROVE",
	REJECT = "REJECT",
	DONE_STATE = "DONE",
	SUBCHECK_PASS = "PASS",
	CHIP_CSCA_TRUSTED = "chip_csca_trusted",
}

export const MANUAL_CHECK_TYPE = {
	IBV: "IBV",
	FALLBACK: "FALLBACK",
};

export const YOTI_SESSION_TOPICS = ["SESSION_COMPLETION", "INSTRUCTIONS_EMAIL_REQUESTED", "THANK_YOU_EMAIL_REQUESTED"];

export const ID_DOCUMENT_TEXT_DATA_EXTRACTION = "ID_DOCUMENT_TEXT_DATA_EXTRACTION";

export const YOTI_CHECKS = {
	IBV_VISUAL_REVIEW_CHECK: {
		"type": "IBV_VISUAL_REVIEW_CHECK",
		"config": {
			"manual_check": MANUAL_CHECK_TYPE.IBV,
		},
	},
	PROFILE_DOCUMENT_MATCH : {
		"type": "PROFILE_DOCUMENT_MATCH",
		"config": {
			"manual_check": MANUAL_CHECK_TYPE.IBV,
		},
	},
	DOCUMENT_SCHEME_VALIDITY_CHECK : {
		"type": "DOCUMENT_SCHEME_VALIDITY_CHECK",
		"config": {
			"manual_check": MANUAL_CHECK_TYPE.IBV,
			"scheme": YOTI_SCHEME_CHECK,
		},
	},
	ID_DOCUMENT_AUTHENTICITY : {
		"type": "ID_DOCUMENT_AUTHENTICITY",
		"config": {
			"manual_check": MANUAL_CHECK_TYPE.FALLBACK,
		},
	},
	ID_DOCUMENT_FACE_MATCH : {
		"type": "ID_DOCUMENT_FACE_MATCH",
		"config": {
			"manual_check": MANUAL_CHECK_TYPE.FALLBACK,
		},
	},
};

export const YOTI_TASKS = {
	ID_DOCUMENT_TEXT_DATA_EXTRACTION: {
		"type": "ID_DOCUMENT_TEXT_DATA_EXTRACTION",
		"config": {
			"manual_check": MANUAL_CHECK_TYPE.FALLBACK,
		},
	},
};

export const YOTI_REQUESTED_CHECKS = [
	YOTI_CHECKS.IBV_VISUAL_REVIEW_CHECK,
	YOTI_CHECKS.PROFILE_DOCUMENT_MATCH,
	YOTI_CHECKS.DOCUMENT_SCHEME_VALIDITY_CHECK,
	YOTI_CHECKS.ID_DOCUMENT_AUTHENTICITY,
	YOTI_CHECKS.ID_DOCUMENT_FACE_MATCH,
];

export const YOTI_REQUESTED_TASKS = [ YOTI_TASKS.ID_DOCUMENT_TEXT_DATA_EXTRACTION];

export const UK_POST_OFFICE = {
	type: "UK_POST_OFFICE",
	name: "UK Post Office Branch",
};
