openapi: 3.0.2
info:
  title:
     Fn::Sub: "${AWS::StackName} - PostOffice Stub Service"
  version: 1.0.0

tags:
  - name: Public Endpoints
    description: Endpoints accessible by the public domain

paths:
  /postoffice/locations/search:
    post:
      tags:
        - Backend Endpoint for Post Office API
      summary: Mock the Post Office location API
      requestBody:
        content:
          application/json:
            schema:
              $ref: "#/components/schemas/LocationSearchPayload"
        required: true
      responses:
        200:
          description: Locations
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/LocationSearchResponse"
      x-amazon-apigateway-request-validator: "both"
      x-amazon-apigateway-integration:
        httpMethod: "POST"
        uri:
          Fn::Sub: arn:aws:apigateway:${AWS::Region}:lambda:path/2015-03-31/functions/arn:aws:lambda:${AWS::Region}:${AWS::AccountId}:function:Post-Office-Stub-${AWS::StackName}:live/invocations
        responses:
          default:
            statusCode: "201"
        passthroughBehavior: "when_no_match"
        contentHandling: "CONVERT_TO_TEXT"
        type: "aws_proxy"

components:
  ## ---------------------
  ## Schema Definitions
  ## ---------------------
  schemas:
    ErrorResponse:
      type: object
      properties:
        code:
          type: string
        message:
          type: string
        errors:
          type: array
          items:
            type: object
            properties:
              property:
                type: string
              message:
                type: string
            required:
              - property
              - message
      required:
        - code
        - message

    LocationSearchPayload:
      type: object
      description: Location Search Payload
      required:
        - searchString
        - productFilter
      properties:
          searchString:
            type: string
            example: SW1A 0AA
            description: >-
              The postcode used for PO location search
          productFilter: 
            type: array
            items:
              type: string
            minItems: 1
            example: ["50321"]
            description: >- 
              Filters out Post Office branches by products they support. “50321” is the code for In-Branch Verification.

    LocationSearchResponse:
      type: object
      description: Location Search Response
      properties:
        metadata:
          type: object
      required:
        - metadata

  ## ---------------------
  ## Response Definitions
  ## ---------------------
  responses:
    500:
      description: Internal Server Error
      content:
        application/json:
          schema:
            $ref: "#/components/schemas/ErrorResponse"
          examples:
            SERVER_ERROR:
              $ref: "#/components/examples/UnexpectedServerError"
    503:
      description: Service Unavailable
      content:
        application/json:
          schema:
            $ref: "#/components/schemas/ErrorResponse"
          examples:
            TEMPORARILY_UNAVAILABLE:
              $ref: "#/components/examples/TemporarilyUnavailableError"
  ## ---------------------
  ## Example Definitions
  ## ---------------------
  examples:
    UnexpectedServerError:
      value:
        code: SERVER_ERROR
        message: An unexpected error occurred on the server
    TemporarilyUnavailableError:
      value:
        code: TEMPORARILY_UNAVAILABLE
        message: Unable to complete your request right now.  Please try again later