AWSTemplateFormatVersion: '2010-09-09'
Transform: AWS::Serverless-2016-10-31
Description: >
  infra-l2-kms

  A set of KMS resources that should be deployed up the environments.

Parameters:
  Environment:
    Description: "The environment type"
    Type: "String"
    Default: dev
    AllowedValues:
      - "dev"
      - "build"
      - "staging"
      - "integration"
      - "production"

  CodeSigningConfigArn:
    Type: String
    Description: >
      The ARN of the Code Signing Config to use, provided by the deployment pipeline
    Default: "none"

  PermissionsBoundary:
    Type: String
    Description: >
      The ARN of the permissions boundary to apply to any role created by the template
    Default: "none"

  KmsPendingWindowInDays:
    Type: Number
    Description: Number of days to retain KMS in pending deletion state when deleted
    Default: 30

Conditions:
  UseCodeSigning:
    Fn::Not:
      - Fn::Equals:
          - !Ref CodeSigningConfigArn
          - "none"

  UsePermissionsBoundary:
    Fn::Not:
      - Fn::Equals:
          - !Ref PermissionsBoundary
          - "none"
  
  CreateDevResources: !Or
    - !Equals [!Ref Environment, 'dev']
    - !Equals [!Ref Environment, 'build']

Globals:
  Function:
    CodeSigningConfigArn: !If
      - UseCodeSigning
      - !Ref CodeSigningConfigArn
      - !Ref AWS::NoValue
    PermissionsBoundary: !If
      - UsePermissionsBoundary
      - !Ref PermissionsBoundary
      - !Ref AWS::NoValue

Resources:
  KMSSigningKey:
    Type: AWS::KMS::Key
    #checkov:skip=CKV_AWS_7:Automatic key rotation can only be enabled on symmetric keys.
    Properties:
      Description: !Sub "${AWS::StackName} VC signing key"
      Enabled: true
      EnableKeyRotation: false
      KeyPolicy:
        Version: "2012-10-17"
        Statement:
          - Effect: Allow
            Principal:
              AWS: !Sub 'arn:aws:iam::${AWS::AccountId}:root'
            Action:
              - "kms:*"
            Resource:
              - "*"
      KeySpec: ECC_NIST_P256
      KeyUsage: SIGN_VERIFY
      MultiRegion: false
      PendingWindowInDays: !Ref KmsPendingWindowInDays
      Tags:
        - Key: KeyType
          Value: VC Signing Key
        - Key: Environment
          Value: !Sub ${Environment}
        - Key: CheckovRulesToSkip
          Value: CKV_AWS_7

  KMSSigningKeyAlias:
    Type: 'AWS::KMS::Alias'
    Properties:
      AliasName: !Sub "alias/${AWS::StackName}-vc-signing-key"
      TargetKeyId: !Ref KMSSigningKey

  KMSEncryptionKey:
    Type: AWS::KMS::Key
    #checkov:skip=CKV_AWS_7:Automatic key rotation can only be enabled on symmetric keys.
    Properties:
      Description: !Sub "${AWS::StackName} CRI encryption key"
      Enabled: true
      KeyPolicy:
        Version: "2012-10-17"
        Statement:
          - Sid: "Allow the account to manage the key"
            Effect: Allow
            Principal:
              AWS: !Sub 'arn:aws:iam::${AWS::AccountId}:root'
            Action: "kms:*"
            Resource: "*"
      KeySpec: RSA_2048
      KeyUsage: ENCRYPT_DECRYPT
      MultiRegion: false
      PendingWindowInDays: !Ref KmsPendingWindowInDays
      Tags:
        - Key: KeyType
          Value: Encryption Key
        - Key: Environment
          Value: !Sub ${Environment}
        - Key: CheckovRulesToSkip
          Value: CKV_AWS_7

  KMSEncryptionKeyAlias:
    Type: 'AWS::KMS::Alias'
    Properties:
      AliasName: !Sub "alias/${AWS::StackName}-encryption-key"
      TargetKeyId: !Ref KMSEncryptionKey

# KMS keys for the IPV stub, only deployed to Dev and Build
  IPVStubSigningKey:
    Type: AWS::KMS::Key
    Condition: CreateDevResources
    Properties:
      Description: A KMS Key for testing signing KMS integration in the development account.
      Enabled: true
      EnableKeyRotation: false
      KeyPolicy:
        Version: "2012-10-17"
        Statement:
          - Effect: Allow
            Principal:
              AWS: !Sub "arn:aws:iam::${AWS::AccountId}:root"
            Action:
              - "kms:*"
            Resource:
              - "*"
      KeySpec: ECC_NIST_P256
      KeyUsage: SIGN_VERIFY
      MultiRegion: false
      PendingWindowInDays: !Ref KmsPendingWindowInDays
      Tags:
        - Key: KeyType
          Value: Test Signing Key
        - Key: Environment
          Value: !Sub ${Environment}
        - Key: CheckovRulesToSkip
          Value: CKV_AWS_7

  IPVStubSigningKeyAlias:
    Type: 'AWS::KMS::Alias'
    Condition: CreateDevResources
    Properties:
      AliasName: !Sub "alias/${AWS::StackName}-ipvstub-signing-key"
      TargetKeyId: !Ref IPVStubSigningKey

  IPVStubAdditionalSigningKey:
    Type: AWS::KMS::Key
    Condition: CreateDevResources
    Properties:
      Description: A additional valid signing key in KMS to reflect multiple JWK's returned by the 'well-known' endpoint
      Enabled: true
      EnableKeyRotation: false
      KeyPolicy:
        Version: "2012-10-17"
        Statement:
          - Effect: Allow
            Principal:
              AWS: !Sub "arn:aws:iam::${AWS::AccountId}:root"
            Action:
              - "kms:*"
            Resource:
              - "*"
      KeySpec: ECC_NIST_P256
      KeyUsage: SIGN_VERIFY
      MultiRegion: false
      PendingWindowInDays: !Ref KmsPendingWindowInDays
      Tags:
        - Key: KeyType
          Value: Test Signing Key
        - Key: Environment
          Value: !Sub ${Environment}
        - Key: CheckovRulesToSkip
          Value: CKV_AWS_7

  IPVStubAdditionalSigningKeyAlias:
    Type: 'AWS::KMS::Alias'
    Condition: CreateDevResources
    Properties:
      AliasName: !Sub "alias/${AWS::StackName}-ipvstub-additional-signing-key"
      TargetKeyId: !Ref IPVStubAdditionalSigningKey

  IPVStubAdditionalEncryptionKey:
    Type: AWS::KMS::Key
    Condition: CreateDevResources
    Properties:
      Description: A unique public encryption key not available at the CRI's /well-known/jwks.json endpoint to test scenarios where decryption fails
      Enabled: true
      EnableKeyRotation: false
      KeyPolicy:
        Version: "2012-10-17"
        Statement:
          - Effect: Allow
            Principal:
              AWS: !Sub "arn:aws:iam::${AWS::AccountId}:root"
            Action:
              - "kms:*"
            Resource:
              - "*"
      KeySpec: RSA_2048
      KeyUsage: ENCRYPT_DECRYPT
      MultiRegion: false
      PendingWindowInDays: !Ref KmsPendingWindowInDays
      Tags:
        - Key: KeyType
          Value: Test Encryption Key
        - Key: Environment
          Value: !Sub ${Environment}
        - Key: CheckovRulesToSkip
          Value: CKV_AWS_7

  IPVStubAdditionalEncryptionKeyAlias:
    Type: 'AWS::KMS::Alias'
    Condition: CreateDevResources
    Properties:
      AliasName: !Sub "alias/${AWS::StackName}-ipvstub-additional-encryption-key"
      TargetKeyId: !Ref IPVStubAdditionalEncryptionKey

Outputs:
  SigningKeyArn:
    Description: "The Arn of the VC signing key"
    Value: !GetAtt KMSSigningKey.Arn
    Export:
      Name: !Sub "${AWS::StackName}-vc-signing-key"
  SigningKeyId:
    Description: "The Id of the VC signing key"
    Value: !Ref KMSSigningKey
    Export:
      Name: !Sub "${AWS::StackName}-vc-signing-key-id"
  SigningKeyAlias:
    Description: "The Alias of the VC signing key"
    Value: !Ref KMSSigningKeyAlias
  EncryptionKeyArn:
    Description: "The ARN of the encryption key"
    Value: !GetAtt KMSEncryptionKey.Arn
    Export:
      Name: !Sub "${AWS::StackName}-encryption-key"
  EncryptionKeyId:
    Description: "The Id of the encryption key"
    Value: !Ref KMSEncryptionKey
    Export:
      Name: !Sub "${AWS::StackName}-encryption-key-id"
  EncryptionKeyAlias:
    Description: "The ARN of the encryption key"
    Value: !Ref KMSEncryptionKeyAlias

# Outputs for IPV stub keys, only referenced in Dev and Build
  IPVStubSigningKeyArn:
    Condition: CreateDevResources
    Description: "The Arn of the IPVStubSigningKey"
    Value: !GetAtt IPVStubSigningKey.Arn
    Export:
      Name: !Sub "${AWS::StackName}-ipvstub-signing-key"
  IPVStubSigningKeyId:
    Condition: CreateDevResources
    Description: "The Id of the IPVStubSigningKey"
    Value: !Ref IPVStubSigningKey
    Export:
      Name: !Sub "${AWS::StackName}-ipvstub-signing-key-id"
  IPVStubSigningKeyAlias:
    Condition: CreateDevResources
    Description: "The Alias of the IPVStubSigningKey"
    Value: !Ref IPVStubSigningKeyAlias
  IPVStubAdditionalSigningKeyArn:
    Condition: CreateDevResources
    Description: "The Arn of the IPVStubAdditionalSigningKey"
    Value: !GetAtt IPVStubAdditionalSigningKey.Arn
    Export:
      Name: !Sub "${AWS::StackName}-ipvstub-additional-signing-key"
  IPVStubAdditionalSigningKeyId:
    Condition: CreateDevResources
    Description: "The Id of the IPVStubAdditionalSigningKey"
    Value: !Ref IPVStubAdditionalSigningKey
    Export:
      Name: !Sub "${AWS::StackName}-ipvstub-additional-signing-key-id"
  IPVStubAdditionalSigningKeyAlias:
    Condition: CreateDevResources
    Description: "The Alias of the IPVStubAdditionalSigningKey"
    Value: !Ref IPVStubAdditionalSigningKeyAlias
  IPVStubAdditionalEncryptionKeyArn:
    Condition: CreateDevResources
    Description: "The Arn of the IPVStubAdditionalEncryptionKey"
    Value: !GetAtt IPVStubAdditionalEncryptionKey.Arn
    Export:
      Name: !Sub "${AWS::StackName}-ipvstub-additional-encryption-key"
  IPVStubAdditionalEncryptionKeyId:
    Condition: CreateDevResources
    Description: "The Id of the IPVStubAdditionalEncryptionKey"
    Value: !Ref IPVStubAdditionalEncryptionKey
    Export:
      Name: !Sub "${AWS::StackName}-ipvstub-additional-encryption-key-id"
  IPVStubAdditionalEncryptionKeyAlias:
    Condition: CreateDevResources
    Description: "The Alias of the IPVStubAdditionalEncryptionKey"
    Value: !Ref IPVStubAdditionalEncryptionKeyAlias
