export const EU_DL_COUNTRIES = [
	{ country: "Austria", alpha3code: "AUT", alpha2code: "AT" },
	{ country: "Belgium", alpha3code: "BEL", alpha2code: "BE" },
	{ country: "Bulgaria", alpha3code: "BGR", alpha2code: "BG" },
	{ country: "Croatia", alpha3code: "HRV", alpha2code: "HR" },
	{ country: "Cyprus", alpha3code: "CYP", alpha2code: "CY" },
	{ country: "Czech Republic", alpha3code: "CZE", alpha2code: "CZ" },
	{ country: "Denmark", alpha3code: "DNK", alpha2code: "DK" },
	{ country: "Estonia", alpha3code: "EST", alpha2code: "EE" },
	{ country: "Finland", alpha3code: "FIN", alpha2code: "FI" },
	{ country: "France", alpha3code: "FRA", alpha2code: "FR" },
	{ country: "Germany", alpha3code: "DEU", alpha2code: "DE" },
	{ country: "Greece", alpha3code: "GRC", alpha2code: "GR" },
	{ country: "Hungary", alpha3code: "HUN", alpha2code: "HU" },
	{ country: "Italy", alpha3code: "ITA", alpha2code: "IT" },
	{ country: "Ireland", alpha3code: "IRL", alpha2code: "IE" },
	{ country: "Latvia", alpha3code: "LVA", alpha2code: "LV" },
	{ country: "Lithuania", alpha3code: "LTU", alpha2code: "LT" },
	{ country: "Luxembourg", alpha3code: "LUX", alpha2code: "LU" },
	{ country: "Malta", alpha3code: "MLT", alpha2code: "MT" },
	{ country: "Netherlands", alpha3code: "NLD", alpha2code: "NL" },
	{ country: "Poland", alpha3code: "POL", alpha2code: "PL" },
	{ country: "Portugal", alpha3code: "PRT", alpha2code: "PT" },
	{ country: "Romania", alpha3code: "ROU", alpha2code: "RO" },
	{ country: "Slovakia", alpha3code: "SVK", alpha2code: "SK" },
	{ country: "Slovenia", alpha3code: "SVN", alpha2code: "SI" },
	{ country: "Spain", alpha3code: "ESP", alpha2code: "ES" },
	{ country: "Sweden", alpha3code: "SWE", alpha2code: "SE" },
];
