export enum AuthSessionState {
	F2F_SESSION_CREATED = "F2F_SESSION_CREATED",
	F2F_AUTH_CODE_ISSUED = "F2F_AUTH_CODE_ISSUED",
	F2F_ACCESS_TOKEN_ISSUED = "F2F_ACCESS_TOKEN_ISSUED",
	F2F_SESSION_ABORTED = "F2F_SESSION_ABORTED",
	F2F_DATA_RECEIVED = "F2F_DATA_RECEIVED",
}
