export enum ServicesEnum {
	SESSION_SERVICE = "F2F_SESSION_SERVICE",
	AUTHORIZATION_SERVICE = "F2F_AUTHORIZATION_SERVICE",
	ACCESS_TOKEN_SERVICE = "F2F_ACCESS_TOKEN_SERVICE",
	DOCUMENT_SELECTION_SERVICE = "F2F_DOCUMENT_SELECTION_SERVICE",
	JWKS_SERVICE = "F2F_JWKS_SERVICE",
	USERINFO_SERVICE = "F2F_USER_INFO_SERVICE",
	GOV_NOTIFY_SERVICE = "F2F_GOV_NOTIFY_SERVICE",
	CALLBACK_SERVICE = "F2F_CALLBACK_SERVICE",
	NA = "NA",
}
