version = 0.1
[dev]
[dev.deploy]
[dev.deploy.parameters]
stack_name = "f2f-backup-monitoring"
s3_prefix = "f2f-backup-monitoring"
region = "eu-west-2"
confirm_changeset = false
capabilities = "CAPABILITY_IAM"
parameter_overrides = "Environment=\"non-prod\" SlackChannelId=\"C04PBBPM4KU\""