name: Deploy Custom Dev Stack for Pull Request

on:
  pull_request:
    branches:
      - main  # Trigger when there's a PR targeting the main branch

permissions:
  id-token: write
  contents: read

env:
  AWS_REGION: eu-west-2

jobs:
  deploy-dev:
    name: Deploy Custom DEV Stack for PR
    runs-on: ubuntu-latest
    steps:
      - name: Check out repository code
        uses: actions/checkout@v4

      - name: Setup SAM CLI
        uses: aws-actions/setup-sam@v2
        with:
          use-installer: true

      - name: Assume temporary AWS role for DEV
        uses: aws-actions/configure-aws-credentials@v4
        with:
          role-to-assume: ${{ secrets.DEV_CRI_F2F_GH_ACTIONS_ROLE_ARN }}
          aws-region: ${{ env.AWS_REGION }}

      - name: Change to Deployment Directory
        run: cd ./deploy

      - name: SAM Validate
        run: sam validate --region ${{ env.AWS_REGION }} -t template.yaml

      - name: SAM Build
        run: sam build -t template.yaml

      - name: Deploy Custom Stack to DEV
        env:
          S3_BUCKET: ${{ secrets.DEV_CRI_F2F_ARTIFACT_SOURCE_BUCKET_NAME }}
        run: |
          sam deploy \
            --resolve-s3 \
            --stack-name "${GITHUB_HEAD_REF}" \
            --s3-prefix $S3_PREFIX \
            --confirm-changeset \
            --config-env dev \
            --parameter-overrides \
              CodeSigningConfigArn="none" \
              Environment="dev" \
              PermissionsBoundary="none" \
              SecretPrefix="none" \
              VpcStackName="vpc-cri" \
              L2DynamoStackName="f2f-cri-ddb" \
              L2KMSStackName="f2f-cri-kms" 
