name: Deploy PostOffice Mock to Dev
on:
  workflow_dispatch:
  # Triggers the workflow on push or pull request events but only for the "main" branch
  push:
    branches:
      - main
    paths:
      - 'post-office-stub/**'

permissions:
  id-token: write
  contents: read

env: # Only adding the variables in that are required for
  AWS_REGION: eu-west-2

jobs:
  deploy-to-build:
    name: Validate & Deploy Yoti stub template to Dev Environment
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: post-office-stub
    steps:
      - name: Check out repository code
        uses: actions/checkout@v3

      - name: Setup SAM CLI
        uses: aws-actions/setup-sam@v2
        with:
          use-installer: true

      - name: Assume temporary AWS role
        uses: aws-actions/configure-aws-credentials@v3
        with:
          role-to-assume: ${{ secrets.DEV_PO_MOCK_GH_ACTIONS_ROLE_ARN }}
          aws-region: ${{ env.AWS_REGION }}

      - name: SAM Validate
        run: sam validate --region ${{ env.AWS_REGION }} -t template.yaml

      - name: SAM Build
        run: sam build -t template.yaml

      - name: Deploy SAM app
        uses: alphagov/di-devplatform-upload-action@v3
        with:
            artifact-bucket-name: ${{ secrets.DEV_PO_MOCK_ARTIFACT_SOURCE_BUCKET_NAME }}
            signing-profile-name: ${{ secrets.DEV_CRI_F2F_SIGNING_PROFILE_NAME }}
            working-directory: post-office-stub
            template-file: template.yaml
