name: Deploy KMS Infra

on:
  push:
    branches:
      - main
    paths:
      - 'infra-l2-kms/**'
  workflow_dispatch:
    inputs:
      environment:
        description: 'Deploy to which environment?'
        required: true
        type: choice
        options:
          - DEV
          - BUILD

permissions:
  id-token: write
  contents: read

env:
  AWS_REGION: eu-west-2

jobs:
  setup:
    if: github.event_name == 'push'
    runs-on: ubuntu-latest
    outputs:
      environments: '["DEV", "BUILD"]'
    steps:
      - run: echo "Setting up environments"

  deploy:
    name: Validate & Deploy KMS Infra template
    runs-on: ubuntu-latest
    needs: setup
    defaults:
      run:
        working-directory: infra-l2-kms
    strategy:
      matrix:
        environment: ${{ fromJson(needs.setup.outputs.environments) }}
    steps:
      - name: Check out repository code
        uses: actions/checkout@v4

      - name: Setup SAM CLI
        uses: aws-actions/setup-sam@v2
        with:
          use-installer: true

      - name: Assume temporary AWS role
        uses: aws-actions/configure-aws-credentials@v4
        with:
          role-to-assume: ${{ secrets[format('{0}_F2F_KMS_GH_ACTIONS_ROLE_ARN', matrix.environment)] }}
          aws-region: ${{ env.AWS_REGION }}

      - name: SAM Validate
        run: sam validate --region ${{ env.AWS_REGION }} -t template.yaml

      - name: SAM Build
        run: sam build -t template.yaml

      - name: Deploy SAM app
        uses: alphagov/di-devplatform-upload-action@v3
        with:
            artifact-bucket-name: ${{ secrets[format('{0}_F2F_KMS_ARTIFACT_SOURCE_BUCKET_NAME', matrix.environment)] }}
            working-directory: infra-l2-kms
            template-file: template.yaml
