name: Deploy IPV Stub to Dev Env
on:
  push:
    branches:
      - main
    paths:
      - 'f2f-ipv-stub/**'
  workflow_dispatch:

permissions:
  id-token: write
  contents: read

env:
  AWS_REGION: eu-west-2

jobs:
  deploy-to-dev:
    name: Validate & Deploy SAM template to Dev Envrionment
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: f2f-ipv-stub
    steps:
      - name: Check out repository code
        uses: actions/checkout@v3

      - name: Setup SAM CLI
        uses: aws-actions/setup-sam@v2

      - name: Assume temporary AWS role
        uses: aws-actions/configure-aws-credentials@v1-node16
        with:
          role-to-assume: ${{ secrets.DEV_IPV_STUB_GH_ACTIONS_ROLE_ARN }}
          aws-region: ${{ env.AWS_REGION }}

      - name: SAM Validate
        run: sam validate --region ${{ env.AWS_REGION }} -t template.yaml

      - name: Install Nodejs Npm Esbuild Builder
        run: npm -g install esbuild

      - name: Install Dependencies
        run: npm install

      - name: SAM Build
        run: sam build -t template.yaml

      - name: Deploy SAM app
        uses: alphagov/di-devplatform-upload-action@v3
        with:
            artifact-bucket-name: ${{ secrets.DEV_IPV_STUB_ARTIFACT_SOURCE_BUCKET_NAME }}
            signing-profile-name: ${{ secrets.DEV_CRI_F2F_SIGNING_PROFILE_NAME }}
            working-directory: f2f-ipv-stub
            template-file: template.yaml