name: Deploy Test Harness

on:
  push:
    branches:
      - main
    paths:
      - 'test-harness/**'
      - .github/workflows/post-merge-deploy-test-harness.yml
  workflow_dispatch:
    inputs:
      environment:
        description: 'Deploy to which environment?'
        required: true
        type: choice
        options:
          - DEV
          - BUILD

permissions:
  id-token: write
  contents: read

env:
  AWS_REGION: eu-west-2

jobs:
  setup:
    runs-on: ubuntu-latest
    outputs:
      environments: ${{ steps.set-output.outputs.environments }}
    steps:
      - id: set-output
        run: |
          if [[ "${{ github.event_name }}" == "push" ]]; then
            echo "::set-output name=environments::[\"DEV\",\"BUILD\"]"
          else
            if [[ "${{ github.event.inputs.environment }}" == "BUILD" && "${{ github.ref }}" != "refs/heads/main" ]]; then
              echo "Deployment to BUILD environment is only allowed from the main branch."
              exit 1
            fi
            echo "::set-output name=environments::[\"${{ github.event.inputs.environment }}\"]"
          fi

  deploy:
    name: Validate & Deploy Test Harness
    runs-on: ubuntu-latest
    needs: setup
    defaults:
      run:
        working-directory: test-harness
    strategy:
      matrix:
        environment: ${{ fromJson(needs.setup.outputs.environments) }}
    steps:
      - name: Check out repository code
        uses: actions/checkout@v4

      - name: Setup SAM CLI
        uses: aws-actions/setup-sam@v2
        with:
          use-installer: true

      - name: Assume temporary AWS role
        uses: aws-actions/configure-aws-credentials@v4
        with:
          role-to-assume: ${{ secrets[format('{0}_TEST_HARNESS_GH_ACTIONS_ROLE_ARN', matrix.environment)] }}
          aws-region: ${{ env.AWS_REGION }}

      - name: SAM Validate
        run: sam validate --region ${{ env.AWS_REGION }} -t template.yaml

      - name: SAM Build
        run: sam build -t template.yaml

      - name: Deploy SAM app
        uses: govuk-one-login/devplatform-upload-action@v3.10.1
        with:
            artifact-bucket-name: ${{ secrets[format('{0}_TEST_HARNESS_ARTIFACT_SOURCE_BUCKET_NAME', matrix.environment)] }}
            signing-profile-name: ${{ secrets[format('{0}_CRI_F2F_SIGNING_PROFILE_NAME', matrix.environment)] }}
            working-directory: test-harness
            template-file: .aws-sam/build/template.yaml
