name: Deploy Outbound Proxy Infra to Build
on:
  workflow_dispatch:
  # Triggers the workflow on push or pull request events but only for the "main" branch
  push:
    branches:
      - main
    paths:
      - 'infra-l2-outbound-proxy/**'

permissions:
  id-token: write
  contents: read

env: # Only adding the variables in that are required for 
  AWS_REGION: eu-west-2

jobs:
  deploy-to-build:
    name: Validate & Deploy Outbound Proxy Infra template to Build Envrionment
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: infra-l2-outbound-proxy
    steps:
      - name: Check out repository code
        uses: actions/checkout@v3

      - name: Setup SAM CLI
        uses: aws-actions/setup-sam@v2
        with:
          version: 1.73.0

      - name: Assume temporary AWS role
        uses: aws-actions/configure-aws-credentials@v1-node16
        with:
          role-to-assume: ${{ secrets.BUILD_F2F_PROXY_GH_ACTIONS_ROLE_ARN }}
          aws-region: ${{ env.AWS_REGION }}

      - name: SAM Validate
        run: sam validate --region ${{ env.AWS_REGION }} -t template.yaml

      - name: SAM Build
        run: sam build -t template.yaml

      - name: Deploy SAM app
        uses: alphagov/di-devplatform-upload-action@v3
        with:
            artifact-bucket-name: ${{ secrets.BUILD_F2F_PROXY_ARTIFACT_SOURCE_BUCKET_NAME }}
            working-directory: infra-l2-outbound-proxy
            template-file: template.yaml