name: Deploy Test Harness to Dev Env
on:
  push:
    branches:
      - main
    paths:
      - 'test-harness/**'
  workflow_dispatch:

permissions:
  id-token: write
  contents: read

env:
  AWS_REGION: eu-west-2

jobs:
  deploy-to-dev:
    name: Validate & Deploy SAM template to Dev Environment
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: test-harness
    steps:
      - name: Check out repository code
        uses: actions/checkout@v3

      - name: Setup SAM CLI
        uses: aws-actions/setup-sam@v2
        with:
          use-installer: true

      - name: Assume temporary AWS role
        uses: aws-actions/configure-aws-credentials@v2
        with:
          role-to-assume: ${{ secrets.DEV_TEST_HARNESS_GH_ACTIONS_ROLE_ARN }}
          aws-region: ${{ env.AWS_REGION }}

      - name: SAM Validate
        run: sam validate --region ${{ env.AWS_REGION }} -t template.yaml

      - name: SAM Build
        run: sam build -t template.yaml

      - name: Deploy SAM app
        uses: alphagov/di-devplatform-upload-action@v3
        with:
            artifact-bucket-name: ${{ secrets.DEV_TEST_HARNESS_ARTIFACT_SOURCE_BUCKET_NAME }}
            signing-profile-name: ${{ secrets.DEV_CRI_F2F_SIGNING_PROFILE_NAME }}
            working-directory: test-harness
            template-file: template.yaml
