name: Pull Request CI - WAF Infra
on:
  # Triggers the workflow on push or pull request events but only for the "main" branch.
  pull_request:
    branches:
      - main
    types:
      - opened
      - reopened
      - ready_for_review
      - synchronize
    paths:
      - 'infra-l2-waf/**'
  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

# Required for sam-validate step
permissions:
  id-token: write
  contents: read

env: # Only adding the variables in that are required for 
  AWS_REGION: eu-west-2

jobs:
  run-code-check:
    name: Code Checks
    runs-on: ubuntu-latest
    defaults:
      run:
        shell: bash
        working-directory: infra-l2-waf
    steps:
      - name: Check out repository code
        uses: actions/checkout@v3
        with:
          submodules: true

      - name: Checks if commiting secrets to repo
        uses: pre-commit/action@v3.0.0
        with:
          extra_args: "detect-secrets --all-files"

      - name: Setup nodeJS v18
        uses: actions/setup-node@v3
        with:
          node-version: 18

      - name: Set offline mirror path
        id: offline-mirror-path
        run: echo "mirror-dir=${GITHUB_WORKSPACE}/npm-packages-offline-cache" >> $GITHUB_OUTPUT

      - name: Cache npm offline-mirror
        uses: actions/cache@v3
        with:
          path: ${{ steps.offline-mirror-path.outputs.mirror-dir }}
          key: offline-mirror-oauth

      - name: Install dependencies
        run: npm install

      - name: Run Infra checks
        run: npm run test

  sam-validate:
    name: SAM Validate
    runs-on: ubuntu-latest
    defaults:
      run:
        shell: bash
        working-directory: infra-l2-waf
    steps:
      - name: Check out repository code
        uses: actions/checkout@v3
        with:
          submodules: true

      - name: Setup SAM CLI
        uses: aws-actions/setup-sam@v2
        with:
          version: 1.70.0
        
      - name: Assume temporary AWS role
        uses: aws-actions/configure-aws-credentials@v1-node16
        with:
          role-to-assume: ${{ secrets.GH_WAF_VALIDATE_ROLE_ARN }}
          aws-region: ${{ env.AWS_REGION }}

      - name: SAM Validate
        run: sam validate --region ${{ env.AWS_REGION }} -t template.yaml

      - name: SAM Build
        run: sam build -t template.yaml
